version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  build-and-unittest:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run:
          name: Check Version
          command: dotnet --version
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore CirclCiDemo.WebApplication
      - run:
          name: Build project 
          command: dotnet build CirclCiDemo.WebApplication
      - run:
          name: "Running tests"
          command: |
              echo "Hello Mohammed From Test Commands"
#             mkdir test-results
#             dotnet test ./Cfd.Tests --logger:"junit;LogFilePath=test-results/dotnet-sample-cfd/xunit.xml"
#       - store_test_results:
#           path: ./Cfd.Tests/test-results
#       - store_artifacts:
#           path: ./Cfd.Tests/test-results