version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  build-and-unittest:
    jobs:
      - build-and-test
      - build-and-test-1
      - build-and-test-2
jobs:
  build-and-test-1:
    executor:
      name: win/default
      version: edge
    steps:
      - run:
          name: "Running tests"
          command: |
              echo "Hello Mohammed From Test Commands"

  build-and-test-2:
    executor:
      name: win/default
      version: edge
    steps:
      - run:
          name: "Running tests"
          command: |
              docker login -u mohammedalbosifi1990 -p dckr_pat_bKJLR3l2MHzcXJDhHeeM7_qLrmQ
              
  build-and-test:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run:
          name: Check Version
          command: docker --version
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore $test_path
      - run:
          name: Build project 
          command: dotnet build $test_path
